From 0fcbe9197add0689fc0b889a8f2c611b661f8435 Mon Sep 17 00:00:00 2001
From: insilications <boboniboni@gmail.com>
Date: Sun, 2 Aug 2020 03:00:40 -0300
Subject: [PATCH 05/12] Allow the groupadd -g command to fail

It fails for me consistently because I am using the same UID/GID inside
the container as outside and group ID 100 already exists in Clear.
---
 mock/py/mockbuild/buildroot.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/mock/py/mockbuild/buildroot.py b/mock/py/mockbuild/buildroot.py
index 1ed6fdd..f6156aa 100644
--- a/mock/py/mockbuild/buildroot.py
+++ b/mock/py/mockbuild/buildroot.py
@@ -397,7 +397,7 @@ class Buildroot(object):
 
         if self.chrootgid:
             self.doChroot(['/usr/sbin/groupadd', '-g', self.chrootgid, self.chrootgroup],
-                          shell=False, nosync=True)
+                          shell=False, raiseExc=False, nosync=True)
         self.doChroot(shlex.split(self.config['useradd']), shell=False, nosync=True)
         if not self.config['clean']:
             self.uid_manager.changeOwner(self.make_chroot_path(self.homedir))
-- 
2.27.0

