From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
From: Thiago Macieira <thiago.macieira@intel.com>
Date: Tue, 3 Jul 2018 16:38:38 -0700
Subject: [PATCH] Allow the groupadd -g command to fail

It fails for me consistently because I am using the same UID/GID inside
the container as outside and group ID 100 already exists in Clear.

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>
Signed-off-by: Patrick McCarty <patrick.mccarty@intel.com>
---
 mock/py/mockbuild/buildroot.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/mock/py/mockbuild/buildroot.py b/mock/py/mockbuild/buildroot.py
index 797f6f6..a2e01e0 100644
--- a/mock/py/mockbuild/buildroot.py
+++ b/mock/py/mockbuild/buildroot.py
@@ -325,7 +325,7 @@ class Buildroot(object):
 
         if self.chrootgid != 0:
             self.doChroot(['/usr/sbin/groupadd', '-g', dets['gid'], dets['group']],
-                          shell=False, nosync=True)
+                          shell=False, raiseExc=False, nosync=True)
         self.doChroot(shlex.split(self.config['useradd'] % dets), shell=False, nosync=True)
         if not self.config['clean']:
             self.uid_manager.changeOwner(self.make_chroot_path(self.homedir))
