From 60b9d4da1cdb7a1a12ec00882896e473c573860e Mon Sep 17 00:00:00 2001
From: William Douglas <william.douglas@intel.com>
Date: Tue, 23 May 2023 11:39:57 -0700
Subject: [PATCH] Allow the groupadd -g command to fail

It fails for me consistently because I am using the same UID/GID inside
the container as outside and group ID 100 already exists in Clear.

Rebased for mock 2.4 update by Francisco Boni <boboniboni@gmail.com>.

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>
Signed-off-by: Patrick McCarty <patrick.mccarty@intel.com>
Signed-off-by: William Douglas <william.douglas@intel.com>
---
 py/mockbuild/buildroot.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/py/mockbuild/buildroot.py b/py/mockbuild/buildroot.py
index ce00772..89c6d8b 100644
--- a/py/mockbuild/buildroot.py
+++ b/py/mockbuild/buildroot.py
@@ -467,7 +467,7 @@ class Buildroot(object):
 
         if self.chrootgid:
             self.doChroot(['/usr/sbin/groupadd', '-g', self.chrootgid, self.chrootgroup],
-                          shell=False, nosync=True)
+                          shell=False, raiseExc=False, nosync=True)
         self.doChroot(shlex.split(self.config['useradd']), shell=False, nosync=True)
         if not self.config['clean']:
             self.uid_manager.changeOwner(self.make_chroot_path(self.homedir))
-- 
2.40.1

